apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_ENV: {{ .Values.config.APP_ENV }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL }}
  API_BASE_URL: "http://{{ .Values.backend.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.port }}"