apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  # Store your sensitive data here as base64 encoded strings
  API_KEY: {{ .Values.secret.apiKey | b64enc | quote }}
